team: {{ cookiecutter.team_name }}
email: {{ cookiecutter.team_email }}
slack: {{ cookiecutter.project_slack_channel}}
project: {{ cookiecutter.project_type}}
agent: {{ cookiecutter.jenkins_agent_label }}
{% if cookiecutter.code_source -%}
source: {{ cookiecutter.code_source }}
{% endif -%}
{% if cookiecutter.branch -%}
branch: {{ cookiecutter.branch }}
{% endif -%}

stages:
  - build
  - deploy-qa
  - deploy-stb
  - merge-rc
  - dryrun-prod
  - deploy-prod
  - ten-percent-prod
  - health-check-prod
  - rollback-new-prod
  - full-traffic-prod
  - destroy-old-prod

jobs:
  - name: build
    stage: build
    cmd: make package
    branch: latest

  - name: deploy-qa
    stage: deploy-qa
    profile: qa
    cmd: make deploy-qa
    branch: latest

  - name: deploy-stb
    stage: deploy-stb
    when: manual
    profile: qa
    cmd: make deploy-stb
    branch: latest

  - name: merge-rc
    stage: merge-rc
    when: manual
    profile: qa
    cmd: make merge-rc

  - name: dryrun-prod
    stage: dryrun-prod
    when: manual
    profile: prod
    cmd: make dryrun-prod
    branch: release-candidate

  - name: deploy-prod
    stage: deploy-prod
    when: manual
    profile: prod
    cmd: make deploy-prod
    branch: release-candidate

  - name: ten-percent-prod
    stage: ten-percent-prod
    when: manual
    profile: prod
    cmd: make ten-percent-prod
    branch: release-candidate

  - name: health-check-prod
    stage: health-check-prod
    when: manual
    profile: prod
    cmd: make health-check-prod
    branch: release-candidate

  - name: rollback-new-prod
    stage: rollback-new-prod
    when: manual
    profile: prod
    cmd: make rollback-new-prod
    branch: release-candidate

  - name: full-traffic-prod
    stage: full-traffic-prod
    when: manual
    profile: prod
    cmd: make full-traffic-prod
    branch: release-candidate

  - name: destroy-old-prod
    stage: destroy-old-prod
    when: manual
    profile: prod
    cmd: make destroy-old-prod
    branch: release-candidate
