#cd.yml default content is not decided yet is not decided yet,

team: {{ cookiecutter.team_name }}
email: {{ cookiecutter.team_email }}
slack: {{ cookiecutter.project_slack_channel}}
project: {{ cookiecutter.project_type}}
agent: {{ cookiecutter.jenkins_agent_label }}
{% if cookiecutter.code_source -%}
source: {{ cookiecutter.code_source }}
{% endif -%}
{% if cookiecutter.branch -%}
branch: {{ cookiecutter.branch }}
{% endif -%}

stages:
	- build
	- beanstalk-qa
	- merge-rc
	- dryrun-prod
	- beanstalk-prod
	- ten-percent-prod
	- health-check-prod
	- fifty-percent-prod
	- rollback-new-prod
	- full-traffic-prod
	- scaledown-old-prod

jobs:
	- name: build
	  stage: build
	  cmd: make package
	  branch: {{ cookiecutter.branch }}

	- name: beanstalk-qa
	  stage: beanstalk-qa
	  profile: qa
	  cmd: make beanstalk-qa
	  branch: {{ cookiecutter.branch }}

	- name: merge-rc
	  stage: merge-rc
	  when: manual
	  profile: qa
	  cmd: make merge-rc
	  branch: {{ cookiecutter.branch }}

	- name: dryrun-prod
	  stage: dryrun-prod
	  when: manual
	  profile: prod
	  cmd: make dryrun-prod_lms
	  branch: release-candidate

	- name: beanstalk-prod
	  stage: beanstalk-prod
	  when: manual
	  profile: prod
	  cmd: make beanstalk-prod
	  branch: release-candidate

	- name: ten-percent-prod
	  stage: ten-percent-prod
	  when: manual
	  profile: prod
	  cmd: make ten-percent-prod
	  branch: release-candidate

	- name: health-check-prod
	  stage: health-check-prod
	  when: manual
	  profile: prod
	  cmd: make health-check-prod
	  branch: release-candidate

	- name: fifty-percent-prod
 	  stage: fifty-percent-prod
 	  when: manual
   	  profile: prod
 	  cmd: make fifty-percent-prod
  	  branch: release-candidate

	- name: rollback-new-prod
  	  stage: rollback-new-prod
  	  when: manual
  	  profile: prod
  	  cmd: make rollback-new-prod
 	  branch: release-candidate

	- name: full-traffic-prod
 	  stage: full-traffic-prod
  	  when: manual
  	  profile: prod
  	  cmd: make full-traffic-prod
 	  branch: release-candidate

	- name: scaledown-old-prod
  	  stage: scaledown-old-prod
  	  when: manual
	  profile: prod
  	  cmd: make scaledown-old-prod
   	  branch: release-candidate
